### ISSUE TITLE
Support for custom url handling logic

### ISSUE THREAD

**Issue by saileshbro** [flyerhq/flutter_link_previewer#12]
Hi, it would be awesome if we could provide our custom URL handler.

Proposed change
```dart
 LinkPreview(
    ...
    onLinkPressed:(url){
        if(url!=null){
            // handle url here
        }
    }
    text: widget.body,
    ...
  )
```

**Comment by demchenkoalex** [comment]
Hi @saileshbro released in [v2.0.1](https://github.com/flyerhq/flutter_link_previewer/releases/tag/v2.0.1). Thanks for the PR!
