### ISSUE TITLE
how to store url preview in a cache memory , any reference ?

### ISSUE THREAD

**Issue by abraraltaf92** [flyerhq/flutter_link_previewer#14]

**Comment by demchenkoalex** [comment]
Hi @abraraltaf92 what do you mean by cache memory? We provide a callback which returns fetched preview data, what you do with it we don't care, but you need to provide saved preview data to the `LinkPreview` widget in order for the widget to work correctly. The most obvious way to store the data is local state, but it can be whatever you want.

**Comment by abraraltaf92** [comment]
Gotcha! thanks
