### ISSUE TITLE
Can we have a flag to disable image

### ISSUE THREAD

**Issue by Rohithgilla12** [flyerhq/flutter_link_previewer#22]
Thanks for an amazing package.
It would be great if we can have a flag that makes the `preview` image hide.
Thanks

**Comment by demchenkoalex** [comment]
Hi, thanks! Sorry for the late response, was on vacation. Released in [v2.2.0](https://github.com/flyerhq/flutter_link_previewer/releases/tag/v2.2.0). `hideImage` param.

**Comment by Rohithgilla12** [comment]
Awesome great
