### ISSUE TITLE
PreviewData is not type :(

### ISSUE THREAD

**Issue by vimalmistry** [flyerhq/flutter_link_previewer#27]
![Screenshot 2021-07-31 at 8 01 45 PM](https://user-images.githubusercontent.com/3993163/127743134-c1461eaf-9315-4771-93ce-540fd6f6603d.png)

I can not define PreviewData previewData varible for state. and If i define as dynamic. then the argument complain about type.

**Comment by demchenkoalex** [comment]
Hi! Did you imported it?

```dart
import 'package:flutter_chat_types/flutter_chat_types.dart' show PreviewData;
```

**Comment by vimalmistry** [comment]
Working Now. Thanks.
