### ISSUE TITLE
Support Custom Image Builder

### ISSUE THREAD

**Issue by theachoem** [flyerhq/flutter_link_previewer#28]
It would be great to support different image builder, eg. `CachedNetworkImage`, or our own shimmer image widget...
```dart
LinkPreview(
  enableAnimation: true,
  imageBuilder: (context, imageUrl){
    return CachedNetworkImage(imageUrl: imageUrl);
  },
 ...
}
```

**Comment by demchenkoalex** [comment]
Released in [v2.3.0](https://github.com/flyerhq/flutter_link_previewer/releases/tag/v2.3.0)
