### ISSUE TITLE
Issues with the `json_serializable` version

### ISSUE THREAD

**Issue by Rohithgilla12** [flyerhq/flutter_link_previewer#35]
`json_serializable` depends on `json_annotation` and other packages depends on the new version of the same package.

Can you please update `json_serializable` if possible, thanks!

**Comment by Rohithgilla12** [comment]
`flutter_chat_types` depends on the package.

https://github.com/flyerhq/flutter_chat_types
You could update to latest version.

**Comment by demchenkoalex** [comment]
Hey, sorry for the long wait, had health issues. Updated and published in [v2.6.2](https://github.com/flyerhq/flutter_link_previewer/releases/tag/v2.6.2).
