### ISSUE TITLE
Support more one option for selectable link or not

### ISSUE THREAD

**Issue by huynguyennovem** [flyerhq/flutter_link_previewer#41]
Thanks for this useful package. 
But it will be nice if we have one more option that enable/disable link's selectable.

**Comment by demchenkoalex** [comment]
Hey @huynguyennovem I don't understand. Can you elaborate please?

**Comment by huynguyennovem** [comment]
Yes, for eg, the link is selectable as below image. I expect the package has one more option to enable/disable this selectable ability 
<img width="316" alt="Screen Shot 2022-04-04 at 9 35 10 AM" src="https://user-images.githubusercontent.com/29337364/161464686-a1ddc31c-673f-4b27-b0b3-9a4696312985.png">

**Comment by demchenkoalex** [comment]
Ah I see, yeah, should be easy to add. If you use this inside the Flutter Chat UI - it is already added there, `isTextMessageTextSelectable`

**Comment by demchenkoalex** [comment]
I guess this was resolved already.
