### ISSUE TITLE
Twitter post url can not be previewed

### ISSUE THREAD

**Issue by huynguyennovem** [flyerhq/flutter_link_previewer#42]
I tried with some Twitter post urls but it seems the package can not crawl them. For eg:

- [Twitter post](https://twitter.com/KubernetesPod/status/1508998520270774275?s=20&t=JkqwbJ_aq8lOSmo2XxTyxA) -> Only `Twitter` title

But there are some other networks that are good displaying:
- [Reddit post](https://www.reddit.com/r/FlutterDev/comments/s8clet/can_flutter_do_everything_a_native_android_app_can/) -> Good
- [Quora post](https://www.quora.com/How-are-cracked-versions-of-software-created-and-why-are-developers-not-able-to-prevent-it) -> Good

<img width="335" alt="Screen Shot 2022-03-30 at 11 32 21 AM" src="https://user-images.githubusercontent.com/29337364/160752814-9c7e82bd-db0f-41c2-b909-c3f339bbfd02.png">

Pls help to support it! Thanks!

**Comment by demchenkoalex** [comment]
Hey @huynguyennovem this is unfortunately impossible on the front end. Same for Facebook. You need to have a token to access Facebook/Twitter feed to preview a particular post. This can only be done on the backend, there are paid services for that, like https://www.linkpreview.net
