### ISSUE TITLE
how to custom layout UI

### ISSUE THREAD

**Issue by CatEatFishs** [flyerhq/flutter_link_previewer#47]
i want to custom layout ui, how to do? 
thanks!

**Comment by demchenkoalex** [comment]
I don't think it is supported right now, need to add some builder function

**Comment by CatEatFishs** [comment]
yes， maybe add some builder function，My product requires a different UI，thanks！

**Comment by demchenkoalex** [comment]
added in [v3.2.1](https://github.com/flyerhq/flutter_link_previewer/releases/tag/v3.2.1).
