### ISSUE TITLE
Converting non-url text to link

### ISSUE THREAD

**Issue by claptv** [flyerhq/flutter_link_previewer#48]
It converts numbers in the text to a link. For example, '4.7 miles' is converted to 'http://4.27'

**Comment by demchenkoalex** [comment]
oh well :D there is no ideal regex I suppose, maybe some regex expert might see this and fix, because 1 change breaks the other, so I'd leave it as is for now

**Comment by demchenkoalex** [comment]
fixed in [v3.2.1](https://github.com/flyerhq/flutter_link_previewer/releases/tag/v3.2.1).
