### ISSUE TITLE
a newer 'http' version

### ISSUE THREAD

**Issue by yvs2014** [flyerhq/flutter_link_previewer#51]
Hello,

https://github.com/flyerhq/flutter_link_previewer/blob/ada90e20a6347e6345978ba6aec408513548aa9a/pubspec.yaml#L20

What about to update 'http' dependency to 1.0?

Reason (as just one of examples):
0.13.6 prevents to build an app with the last stable versions of flutter_map(5.0.0) and flutter_chat_ui(1.6.8) together

p.s. looks like http-0.13.x is only needed to make some tests with 'dart-code-metrics', which itself in a 'deprecation process'
https://github.com/dart-code-checker/dart-code-metrics/blob/98f908a1ab1370b02a4fec9a6f8d7f7de4ae8f35/README.md?plain=1#L9

**Comment by cristaloleg** [comment]
Looks like there was a problem updating it https://github.com/flyerhq/flutter_link_previewer/pull/50

**Comment by yvs2014** [comment]
@cristaloleg seen that, rejected because of that code checker depends on http-0.13.x.
And that nested dependency prevents to work with not outdated packages. As I can see it, flutter_link_previewer itself can work with http-1.0.0.

**Comment by demchenkoalex** [comment]
same problem as I have in `flutter_chat_ui` where some people want updated dependency and some want old dependency. I bet a lot of 3rd party libs still use old http and they all will be broken and people will complain, on the other hand, some 3rd party update it, and now they are broken and other people complain :D never ending..

**Comment by yvs2014** [comment]
@demchenkoalex I'd not say someone so complains, it's enough to make a fork and get rid of that 3rd party blob which isn't used and gone in a depreaction process that declares itself. It was interesting to know for what it needs in a first place, and no more.

**Comment by vladchuk** [comment]
Perhaps extending the dependency range is an option, something like **http: '>=0.13.0 <2.0.0'** ?
This is what some other projects have done, notably grpc. This would make everyone happy :)

**Comment by yvs2014** [comment]
Yeap, as an option, or as a workarond to keep dependency on 3rd party code checker.
Anyway it also would allow a building with not outdated packages.

**Comment by demchenkoalex** [comment]
Didn't know you can do ranges, I will try this

**Comment by vladchuk** [comment]
Any progress on this? Maybe an estimate? Thanks!

**Comment by demchenkoalex** [comment]
Will do today, sorry, crazy week at my job

**Comment by demchenkoalex** [comment]
Released in v3.2.2

**Comment by vladchuk** [comment]
Excellent. Thank you!
