### ISSUE TITLE
`PreviewData` is not available

### ISSUE THREAD

**Issue by Juliotati** [flyerhq/flutter_link_previewer#52]
> import

![Screenshot 2023-07-04 at 09 55 05](https://github.com/flyerhq/flutter_link_previewer/assets/59662912/ac8ae851-9589-47b7-81ce-e14014ff7e1b)

> usage

![Screenshot 2023-07-04 at 09 56 59](https://github.com/flyerhq/flutter_link_previewer/assets/59662912/fe228d2c-bad7-41e3-9182-ee3c31dc5fc9)

**Comment by demchenkoalex** [comment]
it is in the `flutter_chat_types` lib that is the dependency for the `flutter_link_previewer`. You should be able to get it from types https://github.com/flyerhq/flutter_chat_types/blob/main/lib/src/preview_data.dart
